### ISSUE TITLE
Compose scheduler is not running on demos

### ISSUE THREAD

**Issue by sansagara** [benjigoldberg/udacity-airflow#3]
Greetings @benjigoldberg. I tried running the demos on this repo with compose, but tasks in airflow are never executed. Upon looking at Docker ps, i realized the **demos_scheduler_1**  service is always restarting.

I looked, and it seems this is the error:
```
  File "/usr/local/lib/python3.6/site-packages/kombu/transport/redis.py", line 496, in __init__
    self.Client = self._get_client()
  File "/usr/local/lib/python3.6/site-packages/kombu/transport/redis.py", line 957, in _get_client
    'You have {0.__version__}'.format(redis))
kombu.exceptions.VersionMismatch: Redis transport requires redis-py versions 3.2.0 or later. You have 2.10.6
```

I also looked, and the other folders compose are failing one way or another.
I know this repo may not be one of the most important for you, but it would be nice if you can update it to make it run.

I can also try and fix it if you are willing to take PRs.

All the best,
Leonel

**Comment by sansagara** [comment]
Just an FYI: I was able to make everything run by using the latest images of `puckel/docker-airflow ` on all services.

**Comment by benjigoldberg** [comment]
Hi @sansagara thank you for reporting this issue! I'll get this patched up.

**Comment by benjigoldberg** [comment]
This should be all set now 👍
